'
' Copyright 2021 Byndyusoft
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
'

@startuml frontend

!include common.puml

cloud "Node.js" {
  PACKAGE("eslint-config")
}

folder "Using in modern projects" {
  TEMPLATE("cra-template")

  PACKAGE("stylelint-config")
}

folder "Work in progress" {
  TEMPLATE("ui-testing-template")
}

' cra-template
USE("cra-template", "eslint-config")
USE("cra-template", "stylelint-config")

' ui-testing-template
USE("ui-testing-template", "eslint-config")

@enduml
