'
' Copyright 2021 Byndyusoft
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
'

@startuml nodejs

!include common.puml

folder "Using in modern projects" {
  TEMPLATE("nest-template")
  TEMPLATE("node-base-template")
  TEMPLATE("node-typescript-template")

  PACKAGE("class-validator-extended")
  PACKAGE("eslint-config")
  PACKAGE("nest-dynamic-module")
  PACKAGE("nest-http-client")
  PACKAGE("nest-kafka")
  PACKAGE("nest-opentracing")
  PACKAGE("nest-swagger")
  PACKAGE("node-casc")
  PACKAGE("node-dto-factory")
  PACKAGE("node-pino-logger-factory")
  PACKAGE("node-sonar-coverage-reporter")
  PACKAGE("tsconfig")

  INFRA("node-reusable-workflows")
}

folder "Work in progress" {
  TEMPLATE("nodejs-integration-tests-template")
}

folder "Using in legacy projects" {
  PACKAGE("grpc-timeouts")
  PACKAGE("grpc-tools")
}

' nest-template
EXTENDS("nest-template", "node-typescript-template")
USE("nest-template", "class-validator-extended")
USE("nest-template", "nest-dynamic-module")
USE("nest-template", "nest-http-client")
USE("nest-template", "nest-opentracing")
USE("nest-template", "nest-swagger")
USE("nest-template", "node-dto-factory")
USE("nest-template", "node-pino-logger-factory")
USE("nest-template", "node-sonar-coverage-reporter")

' node-base-template
USE("node-base-template", "eslint-config")

' node-typescript-template
EXTENDS("node-typescript-template", "node-base-template")
USE("node-typescript-template", "tsconfig")

' class-validator-extended
EXTENDS("class-validator-extended", "node-typescript-template")

' nest-dynamic-module
EXTENDS("nest-dynamic-module", "node-typescript-template")

' nest-http-client
EXTENDS("nest-http-client", "node-typescript-template")
USE("nest-http-client", "nest-dynamic-module")

' nest-kafka
EXTENDS("nest-kafka", "node-typescript-template")
USE("nest-kafka", "class-validator-extended")
USE("nest-kafka", "nest-dynamic-module")
USE("nest-kafka", "nest-opentracing")

' nest-opentracing
USE("nest-opentracing", "nest-dynamic-module")

' nest-swagger
EXTENDS("nest-swagger", "node-base-template")

' node-dto-factory
EXTENDS("node-dto-factory", "node-typescript-template")

' node-pino-logger-factory
EXTENDS("node-pino-logger-factory", "node-typescript-template")

' node-sonar-coverage-reporter
EXTENDS("node-sonar-coverage-reporter", "node-typescript-template")

' tsconfig
EXTENDS("tsconfig", "node-base-template")

' grpc-timeouts
USE("grpc-timeouts", "eslint-config")

' node-reusable-workflows
EXTENDS("node-reusable-workflows", "node-base-template")

@enduml
