name: test workflow

on:
  - push
  - pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install dependencies
        run: yarn install --production false --frozen-lockfile --ignore-engines

      - name: lint
        run: yarn run lint
